server:
  port: 8080
  antiCheatBuckets: 100
  antiCheatPeriod: 200ms
  antiCheatMaxConcurrent: 5
  dataDir: data
  shutdownTimeout: 30s
  adminKey: VGhpc0lzQVN1cGVyU2VjcmV0S2V5

db:
  file: db/sphinx.db
