server:
  port: 8080
  antiCheatBuckets: 100
  antiCheatPeriod: 200ms
  antiCheatMaxConcurrent: 5
  dataDir: data
  shutdownTimeout: 30s
  adminKey: VGhpc0lzQVN1cGVyU2VjcmV0S2V5
  puzzleOrder:
    - hello-garage-trip
    - odyssey-tattoo
    - voyage-photos
  deadline: 2025-08-23T23:00:00+02:00

db:
  file: db/sphinx.db
